GET http://localhost:8000/api/animales
###
POST http://localhost:8000/api/animales
Content-Type: application/json

{
    "nombre": "Firulais",
    "cantidadPatas" : 4,
    "color" : "Negro",
    "raza" : {
        "tipo" : "Perro",
        "pais" : {
            "codigo": "123",
            "nombre" : "Schnauzer"
        },
        "colores" : ["Negro", "Sal"] 
    } 
}


